/**
 * backend/migrate_faq_and_categories.cjs
 * ─────────────────────────────────────────────────────────────────────────────
 * Additive migration: creates faq_entries table + category_other_label column.
 * Safe to re-run (fully idempotent via IF NOT EXISTS + PRAGMA checks).
 * Back up events.db before running in production.
 */
const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const dbPath = path.join(__dirname, 'data', 'events.db');
const db = new Database(dbPath);

console.log('[Migration] Target DB:', dbPath);

// ── 1. Backup ────────────────────────────────────────────────────────────────
const backupPath = `${dbPath}.bak-${Date.now()}`;
fs.copyFileSync(dbPath, backupPath);
console.log('[Migration] Backed up to:', backupPath);

// ── 2. Create faq_entries table ──────────────────────────────────────────────
db.exec(`
  CREATE TABLE IF NOT EXISTS faq_entries (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    question      TEXT NOT NULL,
    answer        TEXT NOT NULL,
    category      TEXT DEFAULT 'general',
    display_order INTEGER DEFAULT 0,
    status        TEXT DEFAULT 'published' CHECK(status IN ('published','draft','archived')),
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP
  );
`);
console.log('[Migration] faq_entries table: ready.');

// ── 3. Add category_other_label to events (guarded) ──────────────────────────
const eventsColumns = db.pragma('table_info(events)').map(c => c.name);
if (!eventsColumns.includes('category_other_label')) {
  db.exec('ALTER TABLE events ADD COLUMN category_other_label TEXT;');
  console.log('[Migration] events.category_other_label column: added.');
} else {
  console.log('[Migration] events.category_other_label column: already exists, skipping.');
}

// ── 4. Seed starter FAQ entries if empty ─────────────────────────────────────
const faqCount = db.prepare('SELECT COUNT(*) as c FROM faq_entries').get();
if (faqCount.c === 0) {
  const insert = db.prepare(
    'INSERT INTO faq_entries (question, answer, category, display_order, status) VALUES (?, ?, ?, ?, ?)'
  );
  const faqs = [
    ['What is aSK//YOUTH AI?', 'aSK//YOUTH AI is an AI-powered platform built for the Sangguniang Kabataan (SK) of Barangay Concepcion Dos, Marikina City. It helps SK officials manage events, track attendance, generate documents, and allows youth constituents to query SK programs and submit suggestions — all in one unified system.', 'general', 1, 'published'],
    ['How do I view upcoming SK events?', 'You can view upcoming events by navigating to the "Event Management" module from the sidebar. You can also ask the AI Assistant directly — for example, "What are the upcoming SK events?" — and it will display the latest information from the events database.', 'events', 2, 'published'],
    ['How does QR attendance scanning work?', 'Each SK event has a unique QR code generated by the system. When you scan the QR code using your phone\'s camera or the in-app QR Scanner, your attendance is automatically recorded in real-time. Registered SK members have their account linked; guests enter their name and details manually on the scan screen.', 'attendance', 3, 'published'],
    ['What should I do if the QR code won\'t scan?', 'First, ensure your camera is focused and there is good lighting. If the problem persists, ask the SK officer in charge to rotate/refresh the QR code for that event. You can also approach any SK officer present to have your attendance manually logged.', 'attendance', 4, 'published'],
    ['How do I submit a suggestion or feedback to the SK?', 'Navigate to the "Suggestions" module in the sidebar. Type your suggestion, select a category (e.g., Health, Sports, Community), and submit. SK officers and the Chairperson can review and respond to your suggestion. Submissions can be anonymous.', 'participation', 5, 'published'],
    ['What is the ABYIP?', 'ABYIP stands for Annual Barangay Youth Investment Program. It is the official budget plan for SK-funded youth programs for the year. It outlines all planned projects, their objectives, target beneficiaries, and allocated budgets. You can ask the AI Assistant about specific ABYIP projects by name.', 'general', 6, 'published'],
    ['Can I ask the AI about past SK programs and budgets?', 'Yes! The AI Assistant is knowledgeable about general SK programs and services. For more specific historical program details and budget breakdowns, those may be available to SK officers. Feel free to ask — the assistant will provide what it is authorized to share based on your role.', 'general', 7, 'published'],
    ['Where do I find events happening near me?', 'All SK events are held within Barangay Concepcion Dos, Marikina City, unless otherwise specified. Check the "Event Management" module or ask the AI Assistant: "Are there any events this month?" for a complete list with locations.', 'events', 8, 'published'],
  ];
  const seedMany = db.transaction(rows => rows.forEach(r => insert.run(...r)));
  seedMany(faqs);
  console.log('[Migration] Seeded', faqs.length, 'starter FAQ entries.');
} else {
  console.log('[Migration] faq_entries already has', faqCount.c, 'rows — skipping seed.');
}

db.close();
console.log('[Migration] Done. All changes applied successfully.');
